export const GET_DATA_OVERTIME_REQUEST = 'GET_DATA_OVERTIME_REQUEST';
export const GET_DATA_OVERTIME_SUCCESS = 'GET_DATA_OVERTIME_SUCCESS';
export const GET_DATA_OVERTIME_FAILURE = 'GET_DATA_OVERTIME_FAILURE';

export const CREATE_DATA_OVERTIME_REQUEST = 'CREATE_DATA_OVERTIME_REQUEST';
export const CREATE_DATA_OVERTIME_SUCCESS = 'CREATE_DATA_OVERTIME_SUCCESS';
export const CREATE_DATA_OVERTIME_FAILURE = 'CREATE_DATA_OVERTIME_FAILURE';

export const GET_DATA_OVERTIME_BY_ID_REQUEST = 'GET_DATA_OVERTIME_BY_ID_REQUEST';
export const GET_DATA_OVERTIME_BY_ID_SUCCESS = 'GET_DATA_OVERTIME_BY_ID_SUCCESS';
export const GET_DATA_OVERTIME_BY_ID_FAILURE = 'GET_DATA_OVERTIME_BY_ID_FAILURE';

export const CLEAR_OVERTIME_FEEDBACK = 'CLEAR_OVERTIME_FEEDBACK';
